### ISSUE TITLE
example of makefile

### ISSUE THREAD

**Issue by bpffjl** [GSA/msg_project_template#6]
@jwbowers Could you show us an example of how the makefile works? I assume that it's not just for documentation. Does the makefile run your code somehow?

**Comment by jwbowers** [comment]
For example in a fresh copy of our template and after installing all the packages, we have the example a plot of the dino-correlation plot. The Makefile is here:

```make
# This file tracks how inputs and outputs relate in the project
# We assume you will use it from within the root directory of the project

all: Output/Analysis/dino_plot.pdf

# For example we have two targets or outputs below: dino_data.csv and dino_plot.pdf

# dino_plot.pdf depends on the files: Data/dino_data.csv and the R script dino_plot.R within the
# directory called Scripts/Analysis.

# We use ":" to mean "depends on"

# The second line in each section tells the computer what to do to create the dino_plot.pdf file
# Here it just says to run the file with R

Data/dino_data.csv: Data/make_dino_data.R
        R --file=Data/make_dino_data.R

Output/Analysis/dino_plot.pdf: Data/dino_data.csv Scripts/Analysis/dino_plot.R
        R --file=Scripts/Analysis/dino_plot.R
```

Say I want to know what the Makefile thinks I'd need to do to build the whole project. I'd type `make -n all` at the command line and it would say, "First, I need to make the dino_data.csv file and second the dino_plot.pdf file by running these two lines of R code in order."

```bash
❯ make -n all
R --file=Data/make_dino_data.R
R --file=Scripts/Analysis/dino_plot.R
```

If, instead I didn't what to build the whole project, but just wanted to know what was needed to build dino_data.csv, I'd type `make -n Data/dino_data.csv`:

```bash
❯ make -n Data/dino_data.csv
R --file=Data/make_dino_data.R
```

When I'm read to actually run something, I stop saying `-n`. If I typed `make all`, I'd see both of the R files run in order. And then, if I wanted to build `dino_plot.pdf` again, I would get the following message if it had not been too long since I last built it and/or nothing had changed about `dino_data.csv`.

```bash
> make Output/Analysis/dino_plot.pdf
make: `Output/Analysis/dino_plot.pdf' is up to date.
```

On the other hand if I change anything in `dino_data.csv` or in the code to make `dino_data.csv`, then make will detect this and want to re-run everything that `dino_plot.pdf` depends on.

**Comment by jwbowers** [comment]
Just found this. Maybe this helps. Not sure <https://www.youtube.com/watch?v=d1BQHq2pu0Y >

**Comment by jwbowers** [comment]
See also < https://www.youtube.com/watch?v=ocK6IGB6y9g >

**Comment by bpffjl** [comment]
Thanks @jwbowers! 

One thing that I often do with data preparation is add the date of creation to file name; like `prepared-data-2023-06-02.rdata`. I then use that data for the next step. In the past, I did this, because I sometimes found it necessary to investigate older versions of prepared data when people had specific questions or thought they found issues. I understand that if we were to retain data in github that would not really be an issue, but we aren't going to put data there. 

A couple of ideas to overcome this: 

1. Create a data archive where older versions of the data is stored.
2. Update the makefile with the specific version names depending on the data that is used.

One other thought is that I'm unlikely implement the entire data preparation and analysis process in one go, because for some projects data preparation can take ages (the opm work takes hours). Any thoughts on that?

**Comment by jwbowers** [comment]
Closing this issue. Good questions and ideas. I bet we'll discover more as we go.
